//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buseta_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public Bus()
        {
            this.Route = new HashSet<Route>();
            this.cargo = new HashSet<cargo>();
        }
    
        public int id { get; set; }
        public string brand { get; set; }
        public string color { get; set; }
        public Nullable<int> capacity { get; set; }
    
        public virtual ICollection<Route> Route { get; set; }
        public virtual ICollection<cargo> cargo { get; set; }
    }
}
