//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buseta_DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusetasEntities : DbContext
    {
        public BusetasEntities()
            : base("name=BusetasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bus> Bus { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<EmployeeType> EmployeeType { get; set; }
        public DbSet<PersonInCharge> PersonInCharge { get; set; }
        public DbSet<Route> Route { get; set; }
        public DbSet<RouteSchedule> RouteSchedule { get; set; }
        public DbSet<RouteStudent> RouteStudent { get; set; }
        public DbSet<School> School { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<cargo> cargo { get; set; }
    }
}
