//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buseta_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStudent
    {
        public int id { get; set; }
        public Nullable<int> routeId { get; set; }
        public Nullable<int> studentId { get; set; }
        public Nullable<int> orderInRoute { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Student Student { get; set; }
    }
}
