//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buseta_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.RouteStudent = new HashSet<RouteStudent>();
            this.cargo = new HashSet<cargo>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public Nullable<int> age { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public Nullable<int> personInChargeId { get; set; }
        public Nullable<int> schoolId { get; set; }
    
        public virtual PersonInCharge PersonInCharge { get; set; }
        public virtual ICollection<RouteStudent> RouteStudent { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<cargo> cargo { get; set; }
    }
}
